config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end
  delete '/doses/:id', to: 'doses#destroy', as: 'dose'
  root 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
  has_one_attached :photo
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end

    def article_params
      params.require(:article).permit(:title, :body, :photo)
    end

  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_card.html.erb
<div class="pic-cocktail mb-5">
  <div><h3><%= @cocktail.name %></h3>
  <% @cocktail.doses.each do |dose| %>
    <ul>
      <li>
        <%= dose.ingredient.name %> | <%= dose.description %>
      </li>
    </ul>
  <% end %>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <i class="fas fa-cocktail"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "/", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add a cocktail", "cocktails/new", class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>
<div class ="img-fluid text-center bg-primary" style="background-image: url('https://static-cms.carrefour.fr/sites/default/files/2019-06/apero-banner_page_edito_2880x720_2019.jpg?itok=Dq1Mh--J'); background-repeat: no-repeat; background-size: cover; background-position: center center;">
  <h1 class="p-5 text-white pt"><br>Here the best cocktails<br><strong>we need<br></strong></h1>
</div>
<div class="container text-center">
  <br>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card shadow-sm p-3 mb-3 bg-white rounded border-0">
          <div class="card-description text-decoration-none text-warning">
            <img src="https://res.cloudinary.com/dow6rowa0/image/upload/v1597415957/alcohol-1853327_1920-1_bxltvg.jpg" class="img-fluid" alt="Cocktail">
            <h5 class="p-3"><%= link_to cocktail.name, cocktail_path(cocktail), class: "card-link" %></h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<footer class="page-footer font-small">

  <div class="footer-copyright text-center py-3">© 2020 Copyright TQ - <u>Mentions legales</u>
  </div>

</footer>

app/views/cocktails/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <i class="fas fa-cocktail"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "/", class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>

<div class="container padded mt-5">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.error_notification %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: "btn btn-warning" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <i class="fas fa-cocktail"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "/", class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>

<div class="container padded mt-5">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">


<%= render "card", cocktail: @cocktail %>

<%= link_to "Delete cocktail", cocktail_path(@cocktail),
      method: :delete,
      data: { confirm: "Are you sure?" },
      class: "btn btn-secondary rounded" %>





<%= link_to "back to list", cocktails_path, class: "btn btn-dark rounded" %>
<%= link_to "add ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-warning rounded" %>

app/views/doses/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <i class="fas fa-cocktail"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "/", class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>

<div class="container mt-5">
  <h3>Add an ingredient</h1>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.association :ingredient %>
      <%= f.input :description %>
      <%= f.submit "Submit", class: "btn btn-warning" %>
      <% end %>
      <div class="mt-3">
        <%= link_to "back to list", cocktails_path, class: "btn btn-dark rounded" %>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>